### ISSUE TITLE
use try catch to wrap keen-dataviz / keen-analysis instances

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#31]
errors coming from keen-dataviz and keen-analysis should be handled - displayed to the user, in some box like:
![](https://i.imgur.com/R2Qg7mw.png)

**Comment by dariuszlacheta** [comment]
In my opinion errors from keen-dataviz and keen-analysis should stick to the specific chart, because if there will be many elements on the dashboard, it will be hard to tell where is the problem.

**Comment by adamkasprowicz** [comment]
that's a good idea. So let's display an error box over the specific chart? or in the right column under react-select with saved queries?

**Comment by dariuszlacheta** [comment]
Right now errors are displayed on specific chart, like below:
![Screenshot 2019-07-10 at 09 05 46](https://user-images.githubusercontent.com/47319418/60947925-11724e80-a2f2-11e9-906b-f48527b5ba49.png)

This way is more visible that something is wrong and where. We can just style it to look like an error, because right now is more like an information. Additionally in the viewer we can hide charts with errors.

**Comment by dariuszlacheta** [comment]
This is my proposition of final version for keen-dataviz and keen-analysis errors for specific chart:
![Screenshot 2019-07-10 at 11 14 17](https://user-images.githubusercontent.com/47319418/60956901-f7416c00-a303-11e9-8d76-dd1d3c4ed58b.png)

**Comment by adamkasprowicz** [comment]
looks good to me 👍
