### ISSUE TITLE
2 saved queries but 1 line

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#36]
![](https://i.imgur.com/epE11wp.png)

**Comment by dariuszlacheta** [comment]
This problem is caused because this 2 saved queries have the same analysis_type and event_collection, only filters are different, the name of each line is event_collection + analysis_type, so in this case, both lines are named the same, what is causing problem above. Now for dashboard builder I did a quick fix, but at some point We should handle this case in keen-analysis.

Task for fixing it:
https://github.com/keen/keen-analysis.js/issues/64
